[package]
name = "game-input"
version = "0.0.3"
edition = "2024"

[dependencies]
game-types.workspace = true
bevy = { version = "0.17", default-features = false, features = ["bevy_state"] }
gilrs = "0.11"
tracing = "0.1"
