[package]
name = "game-types"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bevy = { version = "0.18", default-features = false }
